// ============================================================
// 角色数据
// ============================================================
const CHARACTERS = [
    {
        id: 'musk',
        name: '埃隆·马斯克',
        nameEn: 'Elon Musk',
        emoji: '🚀',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Elon_Musk_%28cropped%29.jpg/240px-Elon_Musk_%28cropped%29.jpg',
        wealth: 250_000_000_000,
        currency: 'USD',
        tagline: '科技狂人、Twitter 之王',
        accentColor: '#FFD700',
        bgGrad: 'linear-gradient(135deg, #0a0a1a 0%, #1a0a2e 100%)',
        cardBg: 'rgba(26, 26, 58, 0.8)',
    },
    {
        id: 'jackma',
        name: '马云',
        nameEn: 'Jack Ma',
        emoji: '🐎',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Jack_Ma_2017_%28cropped%29.jpg/240px-Jack_Ma_2017_%28cropped%29.jpg',
        wealth: 35_000_000_000,
        currency: 'USD',
        tagline: '乡村教师、阿里传奇',
        accentColor: '#FF6B35',
        bgGrad: 'linear-gradient(135deg, #0a0a1a 0%, #1a120a 100%)',
        cardBg: 'rgba(58, 42, 26, 0.8)',
    },
    {
        id: 'ponyma',
        name: '马化腾',
        nameEn: 'Pony Ma',
        emoji: '🐧',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/%E9%A9%AC%E5%8C%96%E8%85%BE_-_Pony_Ma_%282020%29.jpg/240px-%E9%A9%AC%E5%8C%96%E8%85%BE_-_Pony_Ma_%282020%29.jpg',
        wealth: 45_000_000_000,
        currency: 'USD',
        tagline: '低调极客、社交帝国',
        accentColor: '#00D4FF',
        bgGrad: 'linear-gradient(135deg, #0a0a1a 0%, #0a1a2e 100%)',
        cardBg: 'rgba(26, 42, 58, 0.8)',
    },
    {
        id: 'huang',
        name: '黄仁勋',
        nameEn: 'Jensen Huang',
        emoji: '💻',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Jensen_Huang_%282023%29.jpg/240px-Jensen_Huang_%282023%29.jpg',
        wealth: 100_000_000_000,
        currency: 'USD',
        tagline: 'AI 教父、皮衣刀客',
        accentColor: '#76B900',
        bgGrad: 'linear-gradient(135deg, #0a0a1a 0%, #0a1a0a 100%)',
        cardBg: 'rgba(26, 58, 26, 0.8)',
    },
    {
        id: 'gates',
        name: '比尔·盖茨',
        nameEn: 'Bill Gates',
        emoji: '🪟',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Bill_Gates_2023.jpg/240px-Bill_Gates_2023.jpg',
        wealth: 130_000_000_000,
        currency: 'USD',
        tagline: '慈善之王、微软之父',
        accentColor: '#00A4EF',
        bgGrad: 'linear-gradient(135deg, #0a0a1a 0%, #0a1a1a 100%)',
        cardBg: 'rgba(26, 42, 42, 0.8)',
    },
    {
        id: 'buffett',
        name: '沃伦·巴菲特',
        nameEn: 'Warren Buffett',
        emoji: '🦁',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Warren_Buffett_2018.jpg/240px-Warren_Buffett_2018.jpg',
        wealth: 140_000_000_000,
        currency: 'USD',
        tagline: '股神、奥马哈先知',
        accentColor: '#FFD700',
        bgGrad: 'linear-gradient(135deg, #0a0a1a 0%, #1a1a0a 100%)',
        cardBg: 'rgba(42, 42, 26, 0.8)',
    },
    {
        id: 'zhang',
        name: '张一鸣',
        nameEn: 'Zhang Yiming',
        emoji: '🎵',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Zhang_Yiming_2023.jpg/240px-Zhang_Yiming_2023.jpg',
        wealth: 55_000_000_000,
        currency: 'USD',
        tagline: '算法之王、字节跳动',
        accentColor: '#FF4444',
        bgGrad: 'linear-gradient(135deg, #0a0a1a 0%, #2e0a0a 100%)',
        cardBg: 'rgba(58, 26, 26, 0.8)',
    },
    {
        id: 'zhong',
        name: '钟睒睒',
        nameEn: 'Zhong Shanshan',
        emoji: '🏭',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Zhong_Shanshan_2021.jpg/240px-Zhong_Shanshan_2021.jpg',
        wealth: 65_000_000_000,
        currency: 'USD',
        tagline: '水中茅台、农夫山泉',
        accentColor: '#00E676',
        bgGrad: 'linear-gradient(135deg, #0a0a1a 0%, #0a1a0a 100%)',
        cardBg: 'rgba(26, 42, 26, 0.8)',
    },
];

// ============================================================
// 品类数据
// ============================================================
const CATEGORIES = [
    { id: 'food',     name: '☕ 美食饮品', icon: '☕' },
    { id: 'daily',    name: '🏠 日用生活', icon: '🏠' },
    { id: 'tech',     name: '📱 科技数码', icon: '📱' },
    { id: 'fashion',  name: '👔 轻奢风尚', icon: '👔' },
    { id: 'travel',   name: '✈️ 尊享旅行', icon: '✈️' },
    { id: 'social',   name: '💃 高端社交', icon: '💃' },
    { id: 'luxury',   name: '💎 极致奢品', icon: '💎' },
    { id: 'company',  name: '🏢 收购公司', icon: '🏢' },
    { id: 'realestate', name: '🏘️ 全球房产', icon: '🏘️' },
];

// ============================================================
// 商品数据
// toast: 加入购物车时弹出的彩蛋文案（仅第一次触发）
// unaffordableForAll: true 表示所有人余额不足（如苹果、Google）
// ============================================================
const ITEMS = [
    // ---- ☕ 美食饮品 ----
    {
        id: 'starbucks',
        name: '星巴克咖啡',
        category: 'food',
        price: 5.99,
        emoji: '☕',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Starbucks_Coffee_Logo.svg/240px-Starbucks_Coffee_Logo.svg.png',
        desc: '一杯中杯拿铁，亿万富翁的标配',
        toast: '作为亿万富翁，你终于实现了星巴克自由！☕',
    },
    {
        id: 'xicha',
        name: '喜茶',
        category: 'food',
        price: 7.50,
        emoji: '🍵',
        desc: '网红奶茶，排队两小时喝到嘴',
        toast: '不用排队直接买，这就是有钱人的快乐吗？🧋',
    },
    {
        id: 'wagyu',
        name: '神户和牛套餐',
        category: 'food',
        price: 350,
        emoji: '🥩',
        desc: '顶级A5和牛，入口即化',
    },
    {
        id: 'maotai',
        name: '茅台飞天',
        category: 'food',
        price: 1999,
        emoji: '🍶',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Kweichow_Moutai_logo.svg/240px-Kweichow_Moutai_logo.svg.png',
        desc: '国酒茅台，越喝越有',
        // toast 按角色在 app.js 中处理
    },
    {
        id: 'michelin',
        name: '米其林三星晚宴',
        category: 'food',
        price: 800,
        emoji: '🍽️',
        desc: '三星主厨定制，一生必吃一次',
        toast: '米其林：欢迎亿万富翁光临 👨‍🍳',
    },
    {
        id: 'lafite',
        name: '82 年拉菲',
        category: 'food',
        price: 15000,
        emoji: '🍷',
        desc: '传说中的82年拉菲，来瓶82年的拉菲',
        toast: '82年的拉菲配99年的雪茄，这才是人生 🫧',
    },

    // ---- 🏠 日用生活 ----
    {
        id: 'toothbrush',
        name: '电动牙刷',
        category: 'daily',
        price: 49,
        emoji: '🪥',
        desc: '智能电动牙刷，刷牙也是科技感',
    },
    {
        id: 'dyson',
        name: '戴森吹风机',
        category: 'daily',
        price: 429,
        emoji: '💨',
        desc: '吹风机中的爱马仕',

        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Dyson_logo.svg/240px-Dyson_logo.svg.png",
        toast: '戴森：感谢富豪的认可 💇‍♂️',
    },
    {
        id: 'lego',
        name: '乐高千年隼',
        category: 'daily',
        price: 849,
        emoji: '🧱',
        desc: '7541块积木，拼到你手软',

        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/LEGO_logo.svg/240px-LEGO_logo.svg.png",
    },
    {
        id: 'switch',
        name: 'Nintendo Switch 2',
        category: 'daily',
        price: 449,
        emoji: '🎮',
        desc: '任天堂最新款，先买再说',

        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Nintendo_Switch_logo.svg/240px-Nintendo_Switch_logo.svg.png",    },
    {
        id: 'sonytv',
        name: '索尼 85寸 电视',
        category: 'daily',
        price: 3999,
        emoji: '📺',
        desc: '85寸大法，客厅就是电影院',

        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Sony_logo.svg/240px-Sony_logo.svg.png",
    },
    {
        id: 'smart-home',
        name: '全屋智能家居',
        category: 'daily',
        price: 50000,
        emoji: '🏠',
        desc: '全屋智能化，躺着把事办了',
    },

    // ---- 📱 科技数码 ----
    {
        id: 'iphone',
        name: 'iPhone 16 Pro Max',
        category: 'tech',
        price: 1599,
        emoji: '📱',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/IPhone_15_Pro_%26_iPhone_15_Pro_Max.jpg/240px-IPhone_15_Pro_%26_iPhone_15_Pro_Max.jpg',
        desc: '最新款苹果，买最贵的配置',
        toast: '买iPhone不需要理由，因为你有钱 💅',
    },
    {
        id: 'macbook',
        name: 'MacBook Pro 16"',
        category: 'tech',
        price: 3499,
        emoji: '💻',
        desc: '顶配M4芯片，剪辑8K不卡顿',

        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/MacBook_Pro_16_inch.svg/240px-MacBook_Pro_16_inch.svg.png",
    },
    {
        id: 'tesla',
        name: '特斯拉 Model S Plaid',
        category: 'tech',
        price: 89990,
        emoji: '🚗',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/2019_Tesla_Model_3_Performance_AWD_Front.jpg/240px-2019_Tesla_Model_3_Performance_AWD_Front.jpg',
        desc: '零百加速1.99秒，电动猛兽',
        // toast 按角色在 app.js 处理
    },
    {
        id: 'h100',
        name: 'NVIDIA H100 GPU',
        category: 'tech',
        price: 35000,
        emoji: '🖥️',
        desc: 'AI训练神器，黄仁勋的快乐卡',

        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/NVIDIA_H100_GPU.jpg/240px-NVIDIA_H100_GPU.jpg",
        // toast 按角色处理
    },
    {
        id: 'server',
        name: '私人服务器集群',
        category: 'tech',
        price: 100000,
        emoji: '🖧',
        desc: '在家搭建自己的数据中心',
    },
    {
        id: 'starlink',
        name: '星链卫星套件',
        category: 'tech',
        price: 2500,
        emoji: '🛰️',
        desc: '马斯克的太空Wi-Fi，全球不断网',

        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Starlink_Logo.svg/240px-Starlink_Logo.svg.png",
    },

    // ---- 👔 轻奢风尚 ----
    {
        id: 'lv-bag',
        name: 'LV Neverfull 手袋',
        category: 'fashion',
        price: 1850,
        emoji: '👜',
        desc: '经典老花，百搭不过时',

        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Louis_Vuitton_logo.svg/240px-Louis_Vuitton_logo.svg.png",
    },
    {
        id: 'rolex',
        name: '劳力士潜航者',
        category: 'fashion',
        price: 10000,
        emoji: '⌚',
        desc: '一劳永逸，绿水鬼',

        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Rolex_logo.svg/240px-Rolex_logo.svg.png",
        toast: '一劳永逸？想多了，买了还想买 ⌚',
    },
    {
        id: 'hermes',
        name: '爱马仕铂金包',
        category: 'fashion',
        price: 30000,
        emoji: '👛',
        desc: '比股票还难买的包，你直接拿下',

        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Hermes_logo.svg/240px-Hermes_logo.svg.png",
    },
    {
        id: 'vca',
        name: '梵克雅宝四叶草项链',
        category: 'fashion',
        price: 5200,
        emoji: '📿',
        desc: '四叶草带来好运',
    },
    {
        id: 'patek',
        name: '百达翡丽鹦鹉螺',
        category: 'fashion',
        price: 80000,
        emoji: '⌚',
        desc: '表王中的表王，排队三年起',

        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Patek_Philippe_logo.svg/240px-Patek_Philippe_logo.svg.png",    },
    {
        id: 'savile',
        name: '定制西装 Savile Row',
        category: 'fashion',
        price: 15000,
        emoji: '🤵',
        desc: '伦敦萨维尔街顶级定制，量体裁衣',
    },

    // ---- ✈️ 尊享旅行 ----
    {
        id: 'maldives',
        name: '马尔代夫私人岛度假',
        category: 'travel',
        price: 50000,
        emoji: '🏝️',
        desc: '独享一座岛，面朝大海',
    },
    {
        id: 'jet',
        name: '私人飞机包机',
        category: 'travel',
        price: 120000,
        emoji: '✈️',
        desc: '湾流G600包机，想飞就飞',
    },
    {
        id: 'cruise',
        name: '奢华环球邮轮',
        category: 'travel',
        price: 250000,
        emoji: '🚢',
        desc: '顶级邮轮套房环游世界80天',
    },
    {
        id: 'space-travel',
        name: '太空旅行',
        category: 'travel',
        price: 450000,
        emoji: '🚀',
        desc: '维珍银河亚轨道飞行，体验失重',
        // toast 按角色处理
    },
    {
        id: 'antarctica',
        name: '南极探险之旅',
        category: 'travel',
        price: 75000,
        emoji: '🧊',
        desc: '豪华探险破冰船，登陆南极大陆',
    },
    {
        id: 'burj',
        name: '迪拜帆船酒店总统套房',
        category: 'travel',
        price: 25000,
        emoji: '🏨',
        desc: '帆船酒店最贵套房，一晚的享受',
    },

    // ---- 💃 高端社交 ----
    {
        id: 'accompanion',
        name: '私人伴游体验（1天）',
        category: 'social',
        price: 10000,
        emoji: '💃',
        desc: '顶级模特伴游，全程奢华体验',
        toast: '这才是高端社交的正确打开方式 💃',
    },
    {
        id: 'celebrity-dinner',
        name: '明星共进晚餐',
        category: 'social',
        price: 50000,
        emoji: '⭐',
        desc: '与一线明星共进私人晚宴',
        toast: '帮我也要个签名 🤩',
    },
    {
        id: 'model-party',
        name: '超模派对包场',
        category: 'social',
        price: 200000,
        emoji: '🎉',
        desc: '私人别墅派对，名模云集',
    },
    {
        id: 'butler',
        name: '专属英式管家（年费）',
        category: 'social',
        price: 100000,
        emoji: '🤵‍♂️',
        desc: '英式管家全年24/7随叫随到',
    },
    {
        id: 'vip-club',
        name: '全球顶级私人会籍',
        category: 'social',
        price: 1000000,
        emoji: '💳',
        desc: '全球顶级私人俱乐部终身会员',
    },
    {
        id: 'hollywood',
        name: '好莱坞红毯礼包',
        category: 'social',
        price: 2000000,
        emoji: '📸',
        desc: '奥斯卡红毯VIP + 明星合影 + 晚宴',
    },

    // ---- 💎 极致奢品 ----
    {
        id: 'bugatti',
        name: '布加迪 Chiron',
        category: 'luxury',
        price: 3_000_000,
        emoji: '🏎️',
        desc: '顶级超跑，极速490km/h',

        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Bugatti_logo_2004.svg/240px-Bugatti_logo_2004.svg.png",        toast: '这车一脚油门下去，半套房没了 🏎️',
    },
    {
        id: 'yacht',
        name: '超级游艇',
        category: 'luxury',
        price: 50_000_000,
        emoji: '🛥️',
        desc: '100米超级游艇，带直升机坪',
    },
    {
        id: 'island',
        name: '私人岛屿',
        category: 'luxury',
        price: 80_000_000,
        emoji: '🏝️',
        desc: '加勒比海私人岛屿，你的王国',
        toast: '岛主你好！请问要取什么岛名？ 🏝️',
    },
    {
        id: 'picasso',
        name: '毕加索名画',
        category: 'luxury',
        price: 140_000_000,
        emoji: '🎨',
        desc: '毕加索真迹，挂在家里当装饰',

        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Pablo_Picasso_Signature.svg/240px-Pablo_Picasso_Signature.svg.png",    },
    {
        id: 'gulfstream',
        name: '湾流 G700 私人飞机',
        category: 'luxury',
        price: 78_000_000,
        emoji: '🛩️',
        desc: '全球最先进公务机，富豪标配',

        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Gulfstream_logo.svg/240px-Gulfstream_logo.svg.png",    },
    {
        id: 'monaco',
        name: '摩纳哥顶层公寓',
        category: 'luxury',
        price: 350_000_000,
        emoji: '🏙️',
        desc: '摩纳哥天际线顶层豪宅，俯瞰地中海',
    },

    // ---- 🏢 收购公司 ----
    {
        id: 'twitter',
        name: 'Twitter（X平台）',
        category: 'company',
        price: 44_000_000_000,
        emoji: '🐦',
        desc: '把蓝色小鸟收入囊中，自由删帖',

        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Logo_of_Twitter.svg/240px-Logo_of_Twitter.svg.png",
        toast: '🎉 欢迎加入俱乐部！现在你可以自由删帖了（不是）',
    },
    {
        id: 'mid-company',
        name: '一家中型科技公司',
        category: 'company',
        price: 5_000_000_000,
        emoji: '🏢',
        desc: '年营收10亿，下个独角兽？',
    },
    {
        id: 'your-building',
        name: '你家小区开发商',
        category: 'company',
        price: 500_000_000,
        emoji: '🏗️',
        desc: '买下开发商，给自己免物业费',
        toast: '以后小区物业见到你都得叫爸爸 🏠',
    },
    {
        id: 'nike',
        name: '耐克公司（勾子那个）',
        category: 'company',
        price: 165_000_000_000,
        emoji: '✅',
        desc: 'Just buy it! 整个公司都是你的',

        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Logo_NIKE.svg/240px-Logo_NIKE.svg.png",
        toast: '以后全球的勾子都归你了 ✅',
    },
    {
        id: 'apple',
        name: '⛔ 苹果公司',
        category: 'company',
        price: 3_000_000_000_000,
        emoji: '🍎',
        desc: '库克：不卖。而且你也买不起 🤷',

        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/240px-Apple_logo_black.svg.png",
        unaffordableForAll: true,
    },
    {
        id: 'google',
        name: '⛔ Google 公司',
        category: 'company',
        price: 1_800_000_000_000,
        emoji: '🔍',
        desc: '佩奇：想得美。而且你也买不起 🤷',
        unaffordableForAll: true,
    },

    // ---- 🏘️ 全球房产 ----
    {
        id: 'beverly',
        name: '比弗利山庄豪宅',
        category: 'realestate',
        price: 50_000_000,
        emoji: '🏡',
        desc: '好莱坞明星做邻居',
        toast: '你的新地址：比弗利山庄 富豪路 1号 📍',
    },
    {
        id: 'ny-penthouse',
        name: '纽约中央公园顶层公寓',
        category: 'realestate',
        price: 80_000_000,
        emoji: '🏙️',
        desc: '俯瞰中央公园，曼哈顿天际线',
    },
    {
        id: 'hawaii',
        name: '夏威夷庄园',
        category: 'realestate',
        price: 120_000_000,
        emoji: '🌴',
        desc: '海滨庄园，私人沙滩',
    },
    {
        id: 'london-mansion',
        name: '伦敦海德公园别墅',
        category: 'realestate',
        price: 200_000_000,
        emoji: '🏛️',
        desc: '伦敦市中心顶级豪宅',
    },
    {
        id: 'onsen',
        name: '日本私人温泉度假村',
        category: 'realestate',
        price: 35_000_000,
        emoji: '♨️',
        desc: '富士山脚下，私汤温泉',
    },
    {
        id: 'palm-island',
        name: '迪拜棕榈岛别墅',
        category: 'realestate',
        price: 45_000_000,
        emoji: '🌊',
        desc: '世界岛别墅，帆船酒店景',
    },
];

// ============================================================
// 贷款系统配置
// ============================================================
const LOAN_CONFIG = {
    bankName: '🏦 欠揍银行',
    slogan: '没有我们不敢贷的，只有你还不起的',
    managerName: '王得花',
    interestRate: 666,     // 年利率 666%
    repaymentYears: 1000,  // 分1000年还清
    monthlyPayment: 0.01,  // 每月还 $0.01
    collateral: '你的左肾 🫁',
    // 贷款阈值彩蛋
    eggThresholds: [
        { min: 0, msg: '恭喜你迈出了负债第一步！王行长：我就喜欢你这样的客户 🤝' },
        { min: 100_000_000_000, msg: '🫁 王行长：两个肾都抵押了，要不考虑一下眼角膜？' },
        { min: 500_000_000_000, msg: '🚨 催收天团正在路上... 建议你换个星球生活 🌍🚀' },
        { min: 1_000_000_000_000, msg: '🥇 恭喜获得『宇宙负翁』称号！王行长：你是我们的 VIP 中 P！' },
    ],
};
